### ISSUE TITLE
NEI Recipe handlers not working correctly

### ISSUE THREAD

**Issue by AnimeniacYuuto** [AnimeniacYuuto/EnhancedInventories#10]
NEI doesn't always show chest recipes concerning upgrades

**Comment by UnitedAppMasters** [comment]
NEI dev version 1.0.4.90 appears to at least partially alleviate this problem.  Manually replaced the NEIServerUtils$1.class and NEIServerUtils.class files in the codechicken\nei path of the EnhancedInventories-1.7.10-1.0.8.jar and it at least partially works before crashing now.  Certainly seems to be very dependent on which version of the NEI api the mod was built against.

**Comment by AnimeniacYuuto** [comment]
Fixed via 5e32a92a64ec771fe0f1c98f0d1749e84c52e944
