### ISSUE TITLE
[Feed Back] 1.1.0

### ISSUE THREAD

**Issue by AnimeniacYuuto** [AnimeniacYuuto/EnhancedInventories#12]
I originally made this mod using the same management concepts as other mods, eg. Iron Chests, BiblioCraft, Better Storage, ect., how ever this has led me to some logistical issues concerning various things in the mod I plan to change in 1.1.0. While i will do the best i can to prevent problems some of these changes may break current worlds using my mod, so while I am already at it I would love to hear your suggestions and feed back for 1.1.0

Currently planned changes include:
(+)Tier System change numerical based tiers as opposed to metal based. For example Improved Chest Mk1, Mk2, Mk3, Mk4, Mk5 as opposed to Stone, Iron, Gold, Diamond, Obsidian. Materials will still exist as a aesthetic option, how ever this will allow for me to more easily add metals in the future and should clean up some of the current NEI spam.
(+)Modular Upgrade vs In Crafting Upgrades, upgrades will only be applied via modules to placed chests as opposed to being crafted onto a chest. Upgrading chests via crafting is/was a logistical nightmare, and the new method will allow for less messy NEI integration in the future. Additionally upgrades will be dropped upon the chest being broken. Alternate variations will not be considered upgrades.
(+)Adjust wood support system to support all planks properly via the ore dictionary on black list basis. This will add support for most mods out there and allow my blocks to better support alternate texture packs.
(+)Adjusting inventories to support security features, as of right now there is no way to add any sort of real security to inventories, while I could stop players from accessing the inventories I could not stop them from extracting items out or putting them in via automation. These changes will also make way for more advanced inventory interactions in the future.

**Comment by InkDragon** [comment]
would it be possible to have ore dictionary support for metals? possibly using the block texture like the plank texture for more aesthetic options. EG having a chest made to look like it is made out of gold with gold banding, or iron with steel banding, ect. 

also will 1.10 be backwards compatible with the previous versions or will we risk loosing all our items when the update comes out?

Otherwise I really like the idea of moving from ore named upgrades to the mk system, as sometimes I like the look of lower tier materials but want the space of higher tier ones.

Really looking forward to the security features and support for more aesthetic options

**Comment by AnimeniacYuuto** [comment]
1) Do you mean replacing the wood texture with others? If so maybe, at that point i would allow you to use any normal block for the center texture and would need to make a way to apply the texture other then crafting.

2) I will be doing everything I can to keep 1.1.0 backwards compatible with 1.0.x but i'm just not positive seeing as the tiers are metadata based.

**Comment by InkDragon** [comment]
1. Yes, though I was just think of wood and metal as to not require to much work

2. well if it isn't that's okay so long as you forwarn users

**Comment by AnimeniacYuuto** [comment]
1. The texture rewrite will already be dynamic based on the block texture, it just a mater of not limiting it to wood types.

2. I will definitely let every one know in the case that the inventories cannot be upgraded nicely, but as of right now I think i will be able to pull it off

**Comment by Crumbology** [comment]
How about a config or setting where we could choose wether to scale up the gui to match the slots or stick with the scrollbar, love the chests, but like to see everything without having to scroll.

**Comment by AnimeniacYuuto** [comment]
I could probably look at adding a Max Row/Max Column config. Could be messy though so we'll see

**Comment by Delerium** [comment]
I agree with Crumbology about the scroll bar.  It's one of the major things I get frustrated with.  If you plan on sticking with the scroll bar, it would also be nice if you could scroll with the mouse wheel instead of having to click-drag the bar.  Either by moving the mouse outside of the box or by hovering over the scroll bar and then using the mouse wheel, that way you can still keep the normal item moving functionality of the mouse wheel when you are hovered over an item.

Also, JABBA dolly support would be nice.

**Comment by AnimeniacYuuto** [comment]
I will be adding the option to set a max row/columns afterwhich it will switch to a scroll bar in the future, as i agree as well that it is nice to see the entire inventory, but at a point this also becomes unfeasible with large inventory sizes. I will also most likely be adding a search bar for such inventories as searching through 200+stack for something per chest can be difficult

As far as scroll wheel functionality that should be available as of 1.0.10 just make sure your mouse isn't over an slot (as I know there is another mod that moves items on scroll wheel and didn't want some odd conflict)

**Comment by Crumbology** [comment]
Awesome, thanks a lot for these improvements, and good luck with your mod :)

**Comment by Timeslice42** [comment]
Yup, this pretty much covers all of the concerns and suggestions I had for the mod. What's your guesstimate on completion time? Weeks? Months? Not this year?

**Comment by AnimeniacYuuto** [comment]
@Timeslice42 I am "hoping" to have 1.1.0 out by the end of April at the latest, but might end up some time in May as I am also working on other projects.

**Comment by Unrepentant-Atheist** [comment]
The upgrade to diamond and emerald makes no sense. Emerald is way rarer than diamond, yet both have the same storage space. Emerald ought to have more storage space.

**Comment by AnimeniacYuuto** [comment]
@Unrepentant-Atheist I have already been considering restructuring the cost of inventory tiers, and will likely be doing so to make sure that all of the tiers have a vanilla recipe

**Comment by Joccob** [comment]
Just like you said, it would be much more convenient to have a search bar in those large chest. And it seems a little bit boring if u just keep increasing the storage the chest. Maybe you can add some chest with special usage, like a chest with crafting table.
