### ISSUE TITLE
Double chests can split and cause a crash if opened.

### ISSUE THREAD

**Issue by ImKonor** [AnimeniacYuuto/EnhancedInventories#13]
A double chest can split into 2 singles, causing a crash if/when opened.

http://pastebin.com/j5cmvKyb

**Comment by AnimeniacYuuto** [comment]
Is this happening on a chunk boundary?

**Comment by gchpaco** [comment]
I had this happen to me just now, and it is happening on a chunk boundary.

**Comment by gchpaco** [comment]
Possibly connected, half of my chests (before I moved them) were not only straddling a chunk boundary but also half of them were chunk loaded and half weren't.

**Comment by gchpaco** [comment]
(note: I don't have any automation feeding into it at present; manual operation only)

**Comment by Claycorp** [comment]
I would like to build on this. Been using the mod for a while now and noticed that lockers break apart quite often and result in the same issue.

Seems to be a sync issue as i don't recall it ever happening in singleplayer.

A quick test on a server shows that teleporting to the specter dimension from random things and back will cause the split. Repeating this in singleplayer doesn't cause the split.

**Comment by AnimeniacYuuto** [comment]
Should be fixed via ec7e2630403cbd586be3c7f98b243902b241f4f8 please try 1.1.0 and reopen if issue persists
