### ISSUE TITLE
[Bug] [Visual] Double chests have z-fighting

### ISSUE THREAD

**Issue by SnowShock35** [AnimeniacYuuto/EnhancedInventories#15]
Hi @AnimeniacYuuto 

I have a bug to report and a small feature request to make. Here are the details.

Forge: 1291
Enhanced Inventories Version: 1.0.8
GPU (Since graphical based I thought it would be a good idea to include this): Asus EAH6670

All of the double chests, as far as I am aware, cause z-fighting when being looked at. Kinda important it gets a fix as I was looking forward to using it in my modpack. 
Also I just wanted to also make the suggestion to have scroll wheel support for the inventories that have it. Would be awesome.
Difficult to provide images of the z-fighting so that's why they weren't included. But the problem seems to occur when the cursor is moved.

**Comment by SnowShock35** [comment]
Note: Fastcraft was being used but I removed it to also test it and still came across the same results.

**Comment by AnimeniacYuuto** [comment]
Dose this also happen with lockers?

**Comment by thephoenixlodge** [comment]
If Snowshock's playing with the mod in my pack (Regrowth) as I suspect he is, then he doesn't have access to lockers. For some reason the recipe for the basic stone level one just doesn't exist in the pack without me touching it at all.

**Comment by AnimeniacYuuto** [comment]
I think I found the issue, but i need to double check dose this issue happen with double metal chests? or just double stone & obsidian chests?

**Comment by SnowShock35** [comment]
All double chests no matter what they are made of

**Comment by SnowShock35** [comment]
And in reply to @thephoenixlodge no I was testing a new pack and I saw that you used it in yours and it looked like a nice replacement from boring old iron chests mod. However this problem only does occur with chests. Lockers seem fine from what I have gathered..

**Comment by AnimeniacYuuto** [comment]
Can I get a mod list from you? Also is this happening to the entire chest or just around were the lid meets the base?

**Comment by SnowShock35** [comment]
I think all over not 100% allot seems to be the lid mostly... and sure here is the modlist http://paste.ee/p/GE5Eh sorry it isn't very good. bit busy

**Comment by AnimeniacYuuto** [comment]
I grabbed the mods in the list but cannot duplicate the issue from what i'm hearing. I'm going to need a video or something other wise i'm trouble shooting blind

**Comment by SnowShock35** [comment]
Huh weird, let me test more and see if I can get you a clip of some kind, Not sure if it might actually be video card related, as in being different models/amd over nvidia cards :/ Will try some stuff and get back to you soon

**Comment by SnowShock35** [comment]
Okay so here is the clip (Might want to turn down the volume it's a tad loud, sorry)
That should explain the issue clearly enough, I hope. Might want to talk to @rwtema about it possibly, he might be able to help idk.
Thanks for all the help so far, and if it is fixable that would be great to get if not no worries for this pack I will just stick with iron chests ;) 

https://www.dropbox.com/s/4yschq188bx6jya/2015-03-25-1421-00.flv?dl=0

**Comment by AnimeniacYuuto** [comment]
found and squashed the render bug with 29fad76b9d7f7c296dd1d28fca189d2569389dd4

working on the scroll bar now

**Comment by AnimeniacYuuto** [comment]
Added scroll wheel functionality with 0d0fdedafe0abb3d242cd7a7fbb0361ea3286524
