### ISSUE TITLE
Crash when upgrading a chest

### ISSUE THREAD

**Issue by Renadarain** [AnimeniacYuuto/EnhancedInventories#16]
Hi,

When trying to upgrade a chest (shift+right click) the client crashes - http://pastebin.com/VSGxCXyS - I'm not sure if I'm doing anything wrong because there are no instructions on how to do what. 

Would it be possible to post those somewhere or create a Minecraft Forum thread? This is a great mod and knowing how to use it properly would be really useful :)

I second the guy that asked for lockable chests too.

Regards,
Pickety

**Comment by Renadarain** [comment]
Another bug:
Chests don't stack once placed and picked up.

**Comment by AnimeniacYuuto** [comment]
Can you tell me how you got your chest converter?

**Comment by AnimeniacYuuto** [comment]
If you got the item from creative or nei the issue should be fixed with cbd58920fa40e7f59cbec23ce0e7334cd8d7b4fe other wise please reopen

**Comment by Renadarain** [comment]
Hi

Yes it was a creative upgrade - tested again and works perfectly.  Sorry about that.  Thanks for the fast reply :)

Regards,
Pickety
