### ISSUE TITLE
isValidForConnection crash

### ISSUE THREAD

**Issue by TheWolfJack** [AnimeniacYuuto/EnhancedInventories#2]
New download and install of your mod (which looks VERY promising and interesting!) and got a crash when attempting to place a chest with shift-click.

Crash log server: http://pastebin.com/3pazr4MW
Crash log client: http://pastebin.com/ubxi44H2

**Comment by AnimeniacYuuto** [comment]
fixed via 49e3ea15a4512b66789919b606cc6aac9d20072f
