### ISSUE TITLE
Standing on top of a chest on a server makes it impossible to move.

### ISSUE THREAD

**Issue by Claycorp** [AnimeniacYuuto/EnhancedInventories#23]
When you jump on a chest (Or walk over it) You get stuck on the chest. Your position keeps getting reset and the only way off is to get lucky and break the chest, fly off or get teleported off.

Lockers do not have this problem.

**Comment by AnimeniacYuuto** [comment]
this should be fixed with ec7e2630403cbd586be3c7f98b243902b241f4f8 but reopen if issue persists
