### ISSUE TITLE
Inventory rendering bug.

### ISSUE THREAD

**Issue by Claycorp** [AnimeniacYuuto/EnhancedInventories#24]
Sometimes the items turn ghost like when inside the inventory.
http://i.imgur.com/CIxNscb.png <-- Piture of the issue.

It seemed easy to replicate by placing an enchanted item in front of the chests but will not happen if placed after the items.

**Comment by AnimeniacYuuto** [comment]
i think this is fixed via ec7e2630403cbd586be3c7f98b243902b241f4f8 but reopen if not
