### ISSUE TITLE
Client Crash with Enhanced Inventories

### ISSUE THREAD

**Issue by MrRoooo** [AnimeniacYuuto/EnhancedInventories#25]
When I put a Improved Tin Sorting Chest (965:7) in my personal crafting area, the client will crash to desktop.

When I put Improved Tin Sorting Chest (965:7) in a crafting table, I lose the Sorting. 

https://mineyourmind.net/forum/attachments/crash-2015-06-27_07-45-34-client-txt.5193/

**Comment by AnimeniacYuuto** [comment]
should be fixed via ec7e2630403cbd586be3c7f98b243902b241f4f8
