### ISSUE TITLE
Inventory Interaction

### ISSUE THREAD

**Issue by TheWolfJack** [AnimeniacYuuto/EnhancedInventories#3]
Might be to early to report/mention this, but figured I might as well.

I've noticed that there is no interaction with InventoryTweaks, no auto sorting or the buttons in the chest GUI.
Also noticed that it appears NEI interaction, for example pressing "u" for uses, doesn't seem to work for items in the chests.

I am using a double stone chest and a single iron chest at the moment in my test world.

**Comment by Fortist** [comment]
Also, Mouse tweaks interaction. Where holding shift and drag clicking to dump full lines of stuff into chests would be nice. Or maybe it's InvTweaks. Im not sure.

**Comment by AnimeniacYuuto** [comment]
Should be fixed as of 096befbefb29db19495e0acd649527b657ef2a09

**Comment by TheWolfJack** [comment]
Very happy and anxious to see this update released!

**Comment by AnimeniacYuuto** [comment]
Finishing up lockers and upgrades before i push it out
