### ISSUE TITLE
Items that move chests don't work

### ISSUE THREAD

**Issue by Zyin055** [AnimeniacYuuto/EnhancedInventories#30]
Items added by other mods that can move containers, such as [JABBA] Dolly, [Chest Transporter] Chest Transporter, and [Mekanism] Cardboard box don't work with the Enhanced Inventory chests. The cardboard box kind of works but it causes a crash if you try to move something when the GUI opens (the GUI shouldn't open in the first place).

**Comment by AnimeniacYuuto** [comment]
I'll see what i can do about fixing the [Mekanism] cardboard box for 1.1.0 but the [JABBA] Dolly, and [Chest Transporter] Transporter is on their end atm

**Comment by AnimeniacYuuto** [comment]
Fixed Mekanism Cardboard box issues via ec7e2630403cbd586be3c7f98b243902b241f4f8
