### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bakaxyf** [AnimeniacYuuto/EnhancedInventories#31]
https://gist.github.com/bakaxyf/63857d08189a9e6bc93e

**Comment by AnimeniacYuuto** [comment]
Looks like your missing CoFH Core, Make sure you have the dependencies

**Comment by bakaxyf** [comment]
Srroy

**Comment by AnimeniacYuuto** [comment]
its cool I should probably add them to the main description so they are easier to find.

**Comment by bakaxyf** [comment]
It need YuutoLib not only CoFH Core.
Can you add auto download like Baubles or CodeChickenLib?

**Comment by AnimeniacYuuto** [comment]
I'll take a look at adding that for YuutoLib for future releases
