### ISSUE TITLE
Crash when search recipe of Size Upgrades and MK II+ chests

### ISSUE THREAD

**Issue by bakaxyf** [AnimeniacYuuto/EnhancedInventories#32]
https://gist.github.com/bakaxyf/ab0386fccf455c4ae50f

**Comment by AnimeniacYuuto** [comment]
Okay I see whats happening there, I'll get a bug fix out tomorrow for that, as well as any other bugs that crop up.

In the mean time removing unused frames from the CompatFrames config should fix the issue

**Comment by AnimeniacYuuto** [comment]
Fixed via b03447649b2bc54f8abf236a88a19125a0b1be1e
