### ISSUE TITLE
Crash after trying to load world after updating to 1.1.1

### ISSUE THREAD

**Issue by ate0ate** [AnimeniacYuuto/EnhancedInventories#34]
http://pastebin.com/zPYb7Mz0

Not sure what is going on here. I do have some Enhanced Inventories chests placed down, but I do not have anything involving ender IO attached to them in any way. Not sure why that is mentioned.

**Comment by AnimeniacYuuto** [comment]
looks to be a redstone check so it could be any chest within 1 block of a enerio machine or conduit.

either way i'll take a look

**Comment by AnimeniacYuuto** [comment]
Fixed with d513f549e8e530eeede75a9323341452b5ca3480

**Comment by ate0ate** [comment]
Yup, I certainly had chests nearby my machines. Thanks so much for the quick fix!

**Comment by AnimeniacYuuto** [comment]
No problem, glad I was able to fix it quickly
