### ISSUE TITLE
[1.1.3]Auto Assembler Redstone Controls disabled not functioning.

### ISSUE THREAD

**Issue by thephoenixlodge** [AnimeniacYuuto/EnhancedInventories#36]
When set to Redstone Control disabled, the auto assembler will not automatically craft, but will if set to low with no adjacent RS signal, or on high with a redstone signal applied.

**Comment by AnimeniacYuuto** [comment]
As of right now "disabled" is supposed to craft once per redstone pulse. However this isn't very intuitive so I'll look at clarifying this, and probably adding more control modes for always crafting and never crafting.
I apologize for the confusion

**Comment by AnimeniacYuuto** [comment]
added additional redstone modes as well as a few gui improvements for the Auto Assembler and Worktable via https://github.com/AnimeniacYuuto/YuutoLib/commit/3208dd398918755b4e862f08a58b4a193234bd64 & 47ebb935314fe6be26707a6225272ba36315d4f2
