### ISSUE TITLE
Crash while placing chest on the wall

### ISSUE THREAD

**Issue by AlexPlus117** [AnimeniacYuuto/EnhancedInventories#37]
Hi Yuuto, everytime I put a chest on the wall the game crashes, but if I place the chest on the floor the game keeps working. Here is the crash-report: http://openeye.openmods.info/crashes/375d2150ec8cf2396d4f7b259cfa3cdc

**Comment by AnimeniacYuuto** [comment]
ah okay looks to be an issues with Railcraft's invisible tiles I'll have a fix up in a bit, in the meantime this "should" be able to be worked around by placing another block first. Sorry for the incovinience

**Comment by AlexPlus117** [comment]
Thanks for the support. I'll wait your release.

**Comment by AlexPlus117** [comment]
Are there news about fixing this issue?

**Comment by AnimeniacYuuto** [comment]
should be fixed with 795ee6b28fbd9dd0e13bac2898cd1fad098c4a69

Sorry for the delay got caught up with other stuff
