### ISSUE TITLE
Missing textures in 1.1.6

### ISSUE THREAD

**Issue by b0bst3r** [AnimeniacYuuto/EnhancedInventories#39]
Hi

In assets\enhancedinventories\textures\items

you have
upgradeFunctionBasic.png
upgradeFunctionHopper.png
upgradeFunctionReinforced.png
upgradeFunctionSecurity.png
upgradeFunctionTrapped.png

However these show up as missing textures in game and according to the Forge log it's looking for 

functionUpgradeBasic.png
functionUpgradeHopper.png
functionUpgradeReinforced.png
functionUpgradeSecurity.png
functionUpgradeTrapped.png

Renaming the textures from the original names to those just above render the textures properly.

**Comment by AnimeniacYuuto** [comment]
1) dose this happen with just enhanced inventories(and pre-reqs)?
2) can i get a mod list from you as i cant seem to reproduce this

this is an odd one as it looks like something is overwriting the unlocalized name with the registry name for some reason, which is throwing off my texture name...

also are the names missing localization?

**Comment by b0bst3r** [comment]
There's the odd missing texture and then there's a clump of missing textures in chromaticcraft but they do seem to be genuinely missing (maybe WIP textures).  As far as I can see Enh Inv is the only one which this happens to where the name switches.  I have this weird feeling it's because of the name function but that's probably me being way off the mark.

Mod List - http://pastebin.com/5B1caNAK

This is a heavily modded pack it's Beyond Reality: Divergence on the ATLauncher: https://www.atlauncher.com/pack/BeyondRealityDivergence

I don't know what you mean by missing localization.

If this is pack specific and not a mistake by yourself I'll being it up with the pack maker.

**Comment by AnimeniacYuuto** [comment]
when i say missing localization, I mean the name displaying as something like "item.enhancedinventories:functionUpgrade.1.name" as opposed to "Hopper Upgrade"

**Comment by b0bst3r** [comment]
No that shows as the proper name.

**Comment by Dominance** [comment]
I myself have not adjusted any configs or altered the mod in any way. You can cross reference the MD5 provided by curse to the one included in Divergence. As for any other mod that would override your own I cannot think of any included.

**Comment by AnimeniacYuuto** [comment]
Haha figured it out! In the SquidUitls Items configs the texture is being overwritten at line 25235(according to note pad)
