### ISSUE TITLE
[Overwrite|Dupe] Funny bug with IronChests

### ISSUE THREAD

**Issue by accessdenied0** [AnimeniacYuuto/EnhancedInventories#40]
Hey @AnimeniacYuuto,

Since you allowed to use your chest in the Ore-Dictionary (which I like really much) this mod runs in recipes overwrite/dupe with IronChests'. If I use for example the basic EnhancedInventory's Chest and try to upgrade to copper or iron, I get the equivalent to the IronChest one (Chopper/Iron Chest).

It is pretty funny in my opinion and not really that big kind of a deal. Mostly because I do not really need IronChests because of your awesome mod...

just wanted to let you know,

access_denied

**Comment by AnimeniacYuuto** [comment]
fixed this issue with 2cf3823c5de4984e4f105e684cb174a1a5be3068
