### ISSUE TITLE
Crash when client tries to render .... something

### ISSUE THREAD

**Issue by qchronod** [AnimeniacYuuto/EnhancedInventories#42]
Recently updated my Regrowth server from 0.7.4 to 0.8.2 and this is the only issue I haven't been able to fix. The world seems to be loading in and I was able to walk around for a minute, but as soon as I turned and the tower that we have all the storage the client instantly crashes. IIRC, the chests have bibliocraft frames on them with items to show whats inside.

Regrowth 0.7.4 was using 1.0.11 (thats when the chests and frames were placed)
The 0.8.2 pack comes with 1.1.6, and I tested updating to 1.1.7 but still the same problem
http://gist.github.com/qchronod/9905f5ce32fea717f0b3

**Comment by AnimeniacYuuto** [comment]
I see whats going on and will get a fix up when i can, may be a bit due to personal issues.

If you can revert back to the 0.7.4 world and remove any/all chest converters being displayed by bibliocraft and re-update that "should" fix the issue in the meantime

**Comment by AnimeniacYuuto** [comment]
Go ahead and double check but 1.1.8 should fix this via 3cced0f8e13e86938cf287292cd857cb0d32a4ba

**Comment by qchronod** [comment]
Looks like that fixed it. Thanks.
