### ISSUE TITLE
Undermentioned inventory issue.

### ISSUE THREAD

**Issue by DEX47** [AnimeniacYuuto/EnhancedInventories#44]
I’m looking for assistance. I have corresponded with you before with positive results and you have insight on how MC 1.7.10 inventories behave. I am experiencing issues with items vanishing when I place and extract them manually from an Enhanced Inventory container with a Refined Relocation sort upgrade applied. I have not delved into trouble shooting this issue to any great extent yet, only that a server reboot resolves the issue for a while. I see there are updates with RR and EI. These updates will be applied today.

Should the issue resurface is there an extended debug output that can help me collect data? My current logs do not show the event.

Additional information for you is that I am also having odd behavior with vanilla inventories where and object manually extracted will sometimes graphically vanish. Placing the object in a valid inventory space and reselecting it will refresh the graphic error. I’m not sure if there is a relation here or not. Items that vanish from EI chests do not reappear using the same method.
Please share if there is a better place for me to post this query.

**Comment by AnimeniacYuuto** [comment]
On the first issue, While testing I have noticed that if you place an item in a chest connected to a refined relocation system the gui does not properly update when an item sorts. So it is possible it just got sorted somewhere and didn't update the gui until you tried to pull the stack back out.

Still trying to duplicate the second issue.

**Comment by DEX47** [comment]
I will duplicate my server and remove all nonessential mods that aren't directly connected to the inventory system I have setup. From there I hope to gather info that maybe of use to you.

**Comment by DEX47** [comment]
I abandoned testing with the latest Refined Relocation version due to stability and function issue. I'll return to useing RefinedRelocation-1.7.10-1.0.8b.jar and EnhancedInventories-1.7.10-1.1.8.jar

**Comment by AnimeniacYuuto** [comment]
yeah i noticed the update to refined relocation when checking out this report, and will be checking that out to clean up any issues before the next update

**Comment by DEX47** [comment]
As luck would have it, I setup my test platform on my primary server, and no inventory issues have shown up as of yet. If no event happens this week then it maybe EnhancedInventories-1.7.10-1.1.8.jar was an effective upgrade for me.

One thing I did notice new behavior for and EI auto sorting inventory, where I pulled out an item from a locker and it vanished on a grab click but placing it back in the locker made the item viable again. That is a positive result. I did this several times to repeat the issue however grabbing and placing items in the locker behaved normally.

Where the original issue the item grabbed would vanish and all items grabbed after that point would also vanish until the server was rebooted.

**Comment by AnimeniacYuuto** [comment]
Is this issue still persisting? I have not yet been able to reproduce it

**Comment by DEX47** [comment]
I have seen the issue appear only once since I set things up for testing using your latest version. Unlike previous times I was not able to repeat the issue when it happened and did not need to reboot the server. Should I get a change to consistently replicate the occurrence I will contact you with my findings. I'm going to close this ticket.

Thank you.

**Comment by DEX47** [comment]
Update for you. I had recently done CoFH retro-Ore Generation on my server and experienced this issue again. This process is of course taxing my server and causes it to fall behind. The event of items vanishing form sorting chests was frequent but inconsistent. The did only vanish when placed into the inventory. I also only experienced item loss on my large sorting chest system and not my small 4 chest/locker test systems. To me it sounds like a client server synchronization issue and a some lack of or failed data checking. Course this still doesn't help isolate this as an issue with EI, RR, Forge, or flat out vanilla 1.7.10.
