### ISSUE TITLE
crash with the autocrafting table

### ISSUE THREAD

**Issue by Turmfalke2** [AnimeniacYuuto/EnhancedInventories#46]
hi,
I am playing regrowth with enhanced inventories 1.1.6. When I place down the autocrafting table and put a recipe in it (1 bucket, 4 fire essence makes one lava bucket) the game crashes.
https://bpaste.net/show/913c3db98cb3

**Comment by AnimeniacYuuto** [comment]
Sorry for the late reply, what inventory are you crafting from? and on what side?

**Comment by Turmfalke2** [comment]
In this case the crafting table was placed on the right side of a crafting table from tinkers construct, but all the required items were placed in auto crafting table's inventory.

I also had it crash when I had two of them placed next to each other.

**Comment by pterodactal666** [comment]
This appears to be a cross-mod interaction bug. It also occurs with an auto assembler next to a Tool Station. [I have re-created the crash and here is a crash log](http://pastebin.com/RkqLiW5V)

**Comment by Yatekko** [comment]
I assume this is related.  Playing Regrowth v0.8.6 with Enhanced Inventories v1.1.8 and Magical Crops v0.1 (first release).  Placed the Auto Assembler next to a double Mk III chest, and put the pattern for a lava bucket (empty bucket, four lava essence).  Upon flipping redstone from High to Disabled, the game crashes.  After logging back in, the Auto Assembler and everything that was in it is gone.

http://pastebin.com/C2WXjZHj

**Comment by AnimeniacYuuto** [comment]
Should be fixed between 1.7.10-1.1.9 and 1.7.10-1.1.10 reopen if not
