### ISSUE TITLE
Compatibility with JABBA and some NEI graphic glitches

### ISSUE THREAD

**Issue by AlexPlus117** [AnimeniacYuuto/EnhancedInventories#47]
Hi Yuuto, I'm here to suggest you a sort of compatibility with JABBA's dollies so that you can move chests everywhere. Also, when I look at Enhanced Inventories' recipes, you can see some graphic glitches like these ones:
![2015-10-31_16 01 07](https://cloud.githubusercontent.com/assets/8421361/10864265/baed6c1e-7fe8-11e5-848f-265f3eb54492.png)
![2015-10-31_16 01 36](https://cloud.githubusercontent.com/assets/8421361/10864266/bb063bd6-7fe8-11e5-854e-b75a338cf4a8.png)
![2015-10-31_16 01 42](https://cloud.githubusercontent.com/assets/8421361/10864267/bb221fae-7fe8-11e5-9c84-789122f953dc.png)

**Comment by AnimeniacYuuto** [comment]
As far as Jabba support goes I am waiting for them to go through their pull requests, I've submitted the code for compatibility, and there is a pull request for finishing their api, as soon as either of those are merged there will be Jabba support,

On the note of NEI I'll look at adding better item look ups for the recipe results

**Comment by AlexPlus117** [comment]
How long are you waiting for your code to be merged?

**Comment by AnimeniacYuuto** [comment]
I made the pull request on the 13th, and the api was submitted on the 20th. It is just a matter of waiting until they get to it, there is nothing else I can do on my end until at least one of those are merged.

In the mean time Inventory has a dolly that will move most blocks, and even let you dump their inventories into other inventories.

**Comment by AlexPlus117** [comment]
I made a JABBA version, which is compatible with Enhanced Inventories, with my friend giuseppeM99: https://www.dropbox.com/s/sf4shtxcywxukuz/Jabba-1.2.1a-fixEI_1.7.10.jar?dl=0

**Comment by AnimeniacYuuto** [comment]
Hahaha awesome, I would just ask that you don't distribute it outside your friends with out PoffesorMobius's premission. Cause that not cool :P obviously

**Comment by AlexPlus117** [comment]
Sure. I wanted to post it here just to let you see what we did, but I won't distribute it anywhere :D

**Comment by AnimeniacYuuto** [comment]
NEI support Improved as of 1.7.10-1.1.10
