### ISSUE TITLE
[Issue] Ticking block entity

### ISSUE THREAD

**Issue by accessdenied0** [AnimeniacYuuto/EnhancedInventories#49]
Hello @AnimeniacYuuto,

I recently used your mod's "Automatic Craftingtable" and placed it between a EnderIO's "Power Bank" a Gany's Surface's Chest and a Extra Utilities "Mircoblock Wall" and I got this after I tried to disable the Redstone Control: http://pastebin.com/EfRftSPs

I guess there is an issue with EnderIO possibly... but I'm not quite sure...

access_denied

**Comment by AnimeniacYuuto** [comment]
Should be fixed as of b38d62de1a54b8238afabe302fe0a65fa1777c07
