### ISSUE TITLE
[Suggestion] Dyeable Chests

### ISSUE THREAD

**Issue by InkDragon** [AnimeniacYuuto/EnhancedInventories#5]
I'd like to suggest the ability to change the color of the chests top wool by either using the appropriate color dye on the chest when it is placed or by crafting the chest + dye in a crafting bench.

**Comment by AnimeniacYuuto** [comment]
Fantastic idea that just hadn't gotten around to being implemented added in 0ec217e4f4b8668f0afb2fcd2d5883b2179873ee
