### ISSUE TITLE
Auto Assemblers disappear with no cause

### ISSUE THREAD

**Issue by tom89194** [AnimeniacYuuto/EnhancedInventories#52]
I have been playing the regrowth pack in single player and I have a "few" auto assemblers scattered around. >15 next to a  drawer system and 8 or 9 working next to some barrels and vanilla chests crafting Blood tanks from Sanguimancy. I have had random disappearances with both sets (I usually make a round when I start the world back up, I have not noticed any disappear without saving and reloading).
I also have trouble with assemblers needing random occasional block? updates when they stop working. redstone signal works fine to get the crafter functioning again

good mod,
Thanks,
tom

**Comment by tom89194** [comment]
I started using the same map as a multiplayer server and have not had any assemblers disappear, this after four or five server stop and startups over the last two days

**Comment by AnimeniacYuuto** [comment]
unless this gets more info there isn't anything I can do about this so I'm going to close the issue
