### ISSUE TITLE
Feature request: a working dolly

### ISSUE THREAD

**Issue by romanticjo** [AnimeniacYuuto/EnhancedInventories#55]
To avoid inventory spill, a dolly type is desirable. The dolly provided by Inventory Tools is too powerful moves _every_ block, allows player to keep in inventory any block with penalties) and doesn't have needed drawbacks to allow use in hard packs (revolution 2).

Consider: 
- Jabba integration for dolly support
- Adding a mod specific dolly.

**Comment by AnimeniacYuuto** [comment]
JABBA dolly integration has been pending for a while nothing I can do there for now.
I won't be adding a dolly to EnhancedInventories. Keep in mind you can white list/black list blocks from the InventoryTools dolly.

I will however look at adding side effects to the dolly in the future.
