### ISSUE TITLE
Custom JSON Compat Frames crafting incorrect upgrade

### ISSUE THREAD

**Issue by Wolfofthenyght** [AnimeniacYuuto/EnhancedInventories#57]
Hello there! So, I changed some of the JSON files to alter recipes for the frames in my modpack, and it looks like for some reason they CRAFT the correct upgrade, but they show the wrong result in NEI. I've seen this happen before in other packs with a lot of ores, and I was hoping you could have a look. Here is a screenshot of my JSON config and the in game result. 

When I press 'r' in NEI on Upgrade Module 6, I get this: http://prntscr.com/aqvxnf

And when I press 'r' in NEI on Upgrade Module 7, I get this (I didn't alter this one, this is the vanilla JSON): http://prntscr.com/aqvzdm

And on Upgrade Module 8: http://prntscr.com/aqvzlo

However, they appear to craft to the correct result: http://prntscr.com/aqw1dl

Let me know if this is something that's fixable from your end, or something in NEI. I'm using the latest version of your mod (along with the latest version of the core) and NEI v1.0.5.118, NEIIntegration 1.1.2, and NEIAddons 1.12.14.40. Thanks so much for any help you can provide! :)

**Comment by AnimeniacYuuto** [comment]
Should be at least improved if not fixed in 1.7.10-1.1.10
