### ISSUE TITLE
Secured Inventories

### ISSUE THREAD

**Issue by InkDragon** [AnimeniacYuuto/EnhancedInventories#6]
Better Storage: https://github.com/copygirl/BetterStorage

Suggesting compatibility to use better storage locks on Enhanced Inventories Chests and lockers, allowing players to secure their inventories in SMP environments.

Alternatively suggesting a way to lock inventories

**Comment by AnimeniacYuuto** [comment]
This is a much trickier request, I don't know how or if I want to implement secured blocks so I'll have to think about it

**Comment by InkDragon** [comment]
thanks for the consideration, I hope you do decide to add such a feature. I pointed out the locks simply because I think they would look lovely with the style of chests and lockers you have

**Comment by AnimeniacYuuto** [comment]
Added in ec7e2630403cbd586be3c7f98b243902b241f4f8
