### ISSUE TITLE
Hopper Upgrade Doesn't Insert into Vanilla Chest

### ISSUE THREAD

**Issue by dougburkhalter** [AnimeniacYuuto/EnhancedInventories#61]
When using a hopper upgrade on a single Improved Chest Mark II (only one I've tried, but doubt it's limited to the Mk II), it does not feed netherrack (the only block tried so far, but again I doubt it's related to the block) directly into a vanilla chest from the top. Placing a vanilla hopper in between, the upgrade works (putting whole stacks in the hopper as the upgrade usually does, meaning it's the chest working and not just the hopper pulling out). Also, having the chest on the bottom to receive from the furnace works fine. I am running the latest version of Improved Inventories, included in the Regrowth modpack.

**Comment by AnimeniacYuuto** [comment]
fixed with 237d3326395c9f906ca369181d2ddc95a13b9953 in 1.1.11
