### ISSUE TITLE
[Suggestion] Compatibility Metallurgy

### ISSUE THREAD

**Issue by InkDragon** [AnimeniacYuuto/EnhancedInventories#7]
Requesting support for Metallurgy Metals.

Metallurgy: https://github.com/TeamMetallurgy/Metallurgy4

**Comment by AnimeniacYuuto** [comment]
I will be adding compatibility for more metals but probably not until 1.8

**Comment by InkDragon** [comment]
Thank you. <3 to bad it has to wait for 1.8

**Comment by AnimeniacYuuto** [comment]
you can now configure metalurgy frames for metalurgy via ec7e2630403cbd586be3c7f98b243902b241f4f8
