### ISSUE TITLE
[Suggestion] Ore Dictionary Based Compatibility

### ISSUE THREAD

**Issue by ScottKillen** [AnimeniacYuuto/EnhancedInventories#8]
Link: http://scottk.us/AncientTrees/

**Comment by AnimeniacYuuto** [comment]
Ore dictionary based compatibility for 1.1.0 should add support for extra trees

**Comment by AnimeniacYuuto** [comment]
Partialiy added in 5e32a92a64ec771fe0f1c98f0d1749e84c52e944

**Comment by AnimeniacYuuto** [comment]
completed in ec7e2630403cbd586be3c7f98b243902b241f4f8
